name: Coverbot | Devhub
description: Quickly determine code coverage.

branding:
  icon: check-circle
  color: blue

inputs:
  format:
    description: file format (currently only `elixir` and `go` are supported)
    required: true
  file:
    description: location of json file
    required: true
  domain:
    description: Domain where your Devhub app is hosted
    required: true
  devhub_api_key:
    description: API key from your Devhub app settings
    required: true
  github_token:
    description: GitHub Token
    required: true
  subdirectory:
    description: If your code is in a subdirectory, specify it here
    required: false
  junit_file:
    description: location of the junit file
    required: false
outputs:
  covered:
    description: Number of lines covered
  relevant:
    description: Number of lines considered relevant
  percentage:
    description: The coverage percentage
runs:
  using: 'node20'
  main: 'dist/index.js'
